{
 "title": "errors-and-retries",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Retry Attempts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(notification_retry_total[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP 5xx Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(http_requests_received_total{status=~\"5..\"}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed Notifications",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(notification_failed_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}