{
 "title": "notification-performance",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Processing Latency",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "histogram_quantile(\r\n  0.95,\r\n  sum(rate(notification_processing_duration_seconds_bucket[1m])) by (le)\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Notifications Received (Gateway)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "rate(http_requests_received_total{route=\"/api/notifications\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Notifications by Type",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "notifications_sent_total{type=\"email|sms|push\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}